version: '3'
services:
#  rabbitmq:
#    image: rabbitmq:latest
#    restart: always
#    hostname: rabbitmq
#    ports:
#      - 15672:15672
#      - 5672:5672
#      - 61613:61613
#    volumes:
#      - ./rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins
#      - ./rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
#      - ./rabbit/rabbitmq.server.definition.json:/etc/rabbitmq/rabbitmq.server.definition.json:ro
#    networks:
#      - dev-network
#    healthcheck:
#      test: rabbitmq-diagnostics -q ping
#      interval: 30s
#      timeout: 30s
#      retries: 3

  dis-manager:
    image: ldfcz/dis-manager:latest
    restart: always
    hostname: dis-manager
    ports:
      - 8181:8181
    healthcheck:
      test: "curl --fail --silent localhost:8181/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5

  dis-worker:
    image: ldfcz/dis-worker:latest
    restart: always
    hostname: dis-worker
    ports:
      - 8182:8182
    healthcheck:
      test: "curl --fail --silent localhost:8182/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5

networks:
  dev-network:
    driver: bridge